### PR TITLE
[MSHARED-788] Add functionality to collect raw dependencies in Maven 3+

### PR DESCRIPTION
**Pull request by belingueres**
Added the funcionality.
No added ITs, instead tested the maven-enforcer-plugin with this version
of m-dependency-tree. Tested and passed all tests with: Maven 3.0.4,
3.0.5, 3.1.0, 3.5.4, 3.6.0. Didn't work with Maven 3.0.0 (sonatype
aether 1.7). Other Maven versions not tested.

### CODE REVIEW

**Comment by slachiewicz** [comment]
We should no longer use maven-artifact-transfer

**Comment by rfscholte** [comment]
merged with https://github.com/apache/maven-dependency-tree/commit/7e225abf11faf1a0114d735b9aa2ca9f0669c694

**Comment by cstamas** [comment]
I don't quite understand why this was merged as is...
* Uses plexus
* Uses AbstractLogEnabled
* Uses nasty reflection pattern from m-artifact-transfer we want to get rid

?

**Comment by rfscholte** [comment]
I'll leave the clean up to somebody else on a separate ticket.

**Comment by belingueres** [comment]
I'm glad this is finally moving forward. Let me know if you need further assistance.

**Comment by rfscholte** [comment]
@belingueres  I've tried to restore all integration-tests, and it seems like the verbose output is less compared the 2.x
I've created the branch https://github.com/apache/maven-dependency-tree/tree/fix-tests , which in still work in progress, but you should be able to see the differences.
I could use an extra set of hands or eyes to get the verbose information complete.

**Comment by belingueres** [comment]
@rfscholte I'll take a look in these days.

**Comment by jira-importer** [comment]
Resolve #80

**Pull request closed without merging**
